---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: directory
  path: _podcast
  label: Podcast
  create: all
  match: "**/*"
  templates:
  - podcast
- type: jekyll-posts
  label: Trade Explained
  create: all
  templates:
  - trade-explained
  - video
  - external-commentary
- type: directory
  path: _series
  label: Series
  create: all
  match: "**/*"
  templates:
  - series
- type: directory
  path: _keywords
  label: Tags
  create: all
  match: "**/*"
  templates:
  - tag
- type: directory
  path: _authors
  label: Authors
  create: all
  match: "**/*"
  templates:
  - author
- type: jekyll-pages
  label: Pages
  create: all
- type: heading
  label: DATA
- type: document
  path: _data/content_types.yaml
  label: Content Types
- type: document
  path: _data/language.yml
  label: Language
- type: document
  path: _data/menus.yml
  label: Menus
- type: document
  path: _data/related_links.yml
  label: Related Links
- type: document
  path: _data/trade_guys.yml
  label: Trade Guys
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
